{% set version = "2.2.0" %}
{% set sha256 = "8051c86c732e78ebaef143f8af8621f9315e346a53c41a63d465c55d5368ea99" %}

package:
  name: nanosim
  version: {{ version }}

source:
  url: https://github.com/bcgsc/NanoSim/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - numpy
    - scipy
    - six
    - htseq
    - minimap2
    - last

  run:
    - python
    - numpy
    - scipy
    - six
    - htseq
    - minimap2
    - last

test:
  commands:
    - read_analysis.py -h

about:
  home: https://github.com/bcgsc/NanoSim
  license: GPL
  summary: 'NanoSim is a fast and scalable read simulator that captures the technology-specific features of ONT data, and allows for adjustments upon improvement of nanopore sequencing technology.'
