{% set name = "comet-ms" %}
{% set version = "2018013" %}
{% set sha256_src_bin_bundle = "040b59a5ffa9071f9f7d04fa22a34b32060af7f65fe1ce3ee1140caf941ea60a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/{{ name }}/files/comet_{{ version }}.zip
  sha256: {{ sha256_src_bin_bundle }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}

test:
  commands:
    - comet.exe -p && rm comet.params.new
    - comet -p && rm comet.params.new

about:
  home: http://comet-ms.sourceforge.net/
  license: Apache License 2.0
  summary: 'Comet is a command line tool that does MS/MS database search.'

extra:
  identifiers:
    - doi:10.1007/s13361-015-1179-x
    - doi:10.1002/pmic.201200439
